version: "3.8"

services:
  nginx_app:
    image: nginx:alpine
    container_name: skdb_nginx_app
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - skdb_app_data:/var/www/html
      - ./nginx/app.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - skdb_network

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
        GITHUB_REPO: ${GITHUB_REPO}
    container_name: skdb_php
    restart: unless-stopped
    volumes:
      - skdb_app_data:/var/www/html
      - .env:/var/www/html/.env
    depends_on:
      - redis
      - db
    networks:
      - skdb_network

  redis:
    image: redis:alpine
    container_name: skdb_redis
    restart: unless-stopped
    command: redis-server --save 15 1 --appendonly yes
    networks:
      - skdb_network

  db:
    image: mariadb:10.6
    container_name: skdb_db
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - skdb_db_data:/var/lib/mysql
    ports:
      - "8336:3306"
    networks:
      - skdb_network

  fe_builder:
    build:
      context: .
      dockerfile: fe/Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
        GITHUB_FE_REPO: ${GITHUB_FE_REPO}
    environment:
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: skdb_fe_builder
    restart: "no"
    volumes:
      - skdb_fe_data:/app
    networks:
      - skdb_network

  nginx_fe:
    image: nginx:alpine
    container_name: skdb_nginx_fe
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      # Mount the FE built assets (from fe_builder) into the Nginx document root.
      - skdb_fe_data:/var/www/html
      - ./nginx/fe.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - skdb_network

volumes:
  skdb_app_data:
  skdb_fe_data:
  skdb_db_data:

networks:
  skdb_network:
