version: "3.8"

services:
  nginx:
    image: nginx:alpine
    container_name: skdb_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - skdb_app_data:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - php
    networks:
      - skdb_network

  php:
    build:
      context: .
      dockerfile: php/Dockerfile
      args:
        GITHUB_USERNAME: ${GITHUB_USERNAME}
        GITHUB_ACCESS_TOKEN: ${GITHUB_ACCESS_TOKEN}
        GITHUB_REPO: ${GITHUB_REPO}
    container_name: skdb_php
    restart: unless-stopped
    volumes:
      - skdb_app_data:/var/www/html
      - .env:/var/www/html/.env  # ✅ Mounts .env file into the container
    depends_on:
      - redis
      - db
    networks:
      - skdb_network

  redis:
    image: redis:alpine
    container_name: skdb_redis
    restart: unless-stopped
    command: redis-server --save 15 1 --appendonly yes
    networks:
      - skdb_network

  db:
    image: mariadb:10.6
    container_name: skdb_db
    restart: unless-stopped
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - skdb_db_data:/var/lib/mysql
    networks:
      - skdb_network

volumes:
  skdb_app_data:
  skdb_db_data:

networks:
  skdb_network:
